# Generated by Django 3.2.3 on 2021-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='placeholder_img.jpg', null=True, upload_to=''),
        ),
    ]
